version: 2.1
orbs:
  node: circleci/node@1.1.6

executors:
  dotnet:
    description: .NET Executor
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0

jobs:
  test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: "Install dependencies"
                command: cd WhaleSpotting/react-app; npm install
            - run:
                name: "Run tests"
                command: cd WhaleSpotting/react-app; npm test
#            Uncomment these lines to run the linter
#            - run:
#                name: "Run lint"
#                command: cd WhaleSpotting/react-app; npm run lint
  test-backend:
    executor: dotnet
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "WhaleSpotting/WhaleSpotting.csproj" }}
      - run:
          name: "Restore project"
          command: dotnet restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "WhaleSpotting/WhaleSpotting.csproj" }}
      - run:
          name: "Run tests"
          command: dotnet test

workflows:
  test:
    jobs:
      - test-frontend
      - test-backend
